/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    alert($(this).text());

  
var city =$(this).text(); 
  $.ajax('https://query.yahooapis.com/v1/public/yql', {   
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '") and u="c" ',
           format: 'json'

         },
         success: function (data) {

skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
skycons.set("day1", Skycons.CLEAR_DAY);
skycons.set("day2", Skycons.CLOUDY);
skycons.set("day3", Skycons.RAIN);

var weatherInfo = data.query.results.channel.item,  
     todaydate = weatherInfo.forecast[0].date;
     $('.date').text(todaydate); 
 var todayweather = weatherInfo.forecast[0].text;
     $('.info').text(todayweather);         
 var  todaytemp = weatherInfo.condition.temp;
     $('.temperature').text(todaytemp);
   
 var  day1date = weatherInfo.forecast[1].date;
     $('.day1').text(day1date);
 var  day1hi = weatherInfo.forecast[1].high;
     $('.day1high').text(day1hi);
 var  day1lo = weatherInfo.forecast[1].low;
     $('.day1low').text(day1lo);
           
 var   day2date = weatherInfo.forecast[2].date;
     $('.day2').text(day2date);
 var   day2hi = weatherInfo.forecast[2].high;
     $('.day2high').text(day2hi);
 var   day2lo = weatherInfo.forecast[2].low;
     $('.day2low').text(day2lo);
           
 var  day3date = weatherInfo.forecast[3].date;
     $('.day3').text(day3date);
 var   day3hi = weatherInfo.forecast[3].high;
     $('.day3high').text(day3hi);
 var  day3lo = weatherInfo.forecast[3].low;
     $('.day3low').text(day3lo);

var weatehrcode = weatherInfo.item.forecast[0].code;
          switch(weathercode){
            case 32:
            case 34:
            case 36:
            skycons.set( "today", Skycons.CLEAR_DAY);
            break;
            case 31:
            case 33:
            skycons.set( "today", Skycons.CLEAR_NIGHT);
            break;
            case 29:
            case 27:
            skycons.set( "today", Skycons.PARTLY_CLOUDY_NIGHT);
            break;
            case 30:
            case 28:
            case 44:
            skycons.set( "today", Skycons.PARTLY_CLOUDY_DAY);
            break;
            case 26:
            skycons.set( "today", Skycons.CLOUDY);
            break;
            case 11:
            case 12:
            case 40:
            case 5:
            case 6:
            case 10:
            skycons.set( "today", Skycons.RAIN);
            break;
            case 18:
            skycons.set( "today", Skycons.SLEET);
            break;
            case 16:
            case 7:
            case 13:
            case 14:
            case 1:
            case 42:
            case 43:
            case 46:
            skycons.set( "today", Skycons.SNOW);
            break;
            case 24:
            skycons.set( "today", Skycons.WIND);
            break;
            case 20:
            skycons.set( "today", Skycons.FOG);
            break;
          }

         }});
 
});